# Generated by Django 5.2 on 2025-04-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('guide', models.CharField(max_length=255, verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Запланированный тур',
                'verbose_name_plural': 'Запланированные туры',
                'db_table': 'scheduled_tours',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('place', models.CharField(max_length=255, verbose_name='Место начала')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('max_members', models.IntegerField(verbose_name='Максимум участников')),
                ('image', models.ImageField(max_length=255, upload_to='images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(default=None, null=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_need_lunch', models.BooleanField(verbose_name='Обед')),
                ('is_need_notify', models.BooleanField(verbose_name='Уведомление')),
                ('count_members', models.IntegerField(verbose_name='Количество человек')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
                ('scheduled_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduledtour', verbose_name='Запланированный тур')),
            ],
            options={
                'verbose_name': 'Запись на тур',
                'verbose_name_plural': 'Записи на тур',
                'db_table': 'entries',
            },
        ),
        migrations.AddField(
            model_name='scheduledtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tour', verbose_name='Тур'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер точки')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(max_length=255, upload_to='images/', verbose_name='Картинка')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Точка остановки',
                'verbose_name_plural': 'Точки остановки',
                'db_table': 'points',
            },
        ),
    ]
