# Generated by Django 5.2 on 2025-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
